name: FTP Deploy

on:
  push:
    branches: [ main ]  # Change to your main branch name if different

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /public_html/speelplaatsruben/wp-content/themes/skelet-theme/
          protocol: ftp  # Plain FTP as shown in your FileZilla
          port: 21  # Standard FTP port
          security: loose  # For insecure plain FTP
          timeout: 180000  # 3 minutes timeout
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            github-deploy-key
            github-deploy-key.pub
            .github/**